// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto-data.proto

package proto_data

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Packet struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadSentTime      int64    `protobuf:"varint,3,opt,name=payload_sent_time,json=payloadSentTime,proto3" json:"payload_sent_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a73d22b223efd8ec, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Packet) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *Packet) GetPayloadSentTime() int64 {
	if m != nil {
		return m.PayloadSentTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Packet)(nil), "proto_data.Packet")
}

func init() { proto.RegisterFile("proto-data.proto", fileDescriptor_a73d22b223efd8ec) }

var fileDescriptor_a73d22b223efd8ec = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4d, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x33, 0x85, 0xb8, 0xc0, 0x54, 0x3c, 0x48, 0x44,
	0x29, 0x8e, 0x8b, 0x2d, 0x20, 0x31, 0x39, 0x3b, 0xb5, 0x44, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88, 0x29, 0x33, 0x45, 0x48, 0x82, 0x8b, 0xbd, 0x20, 0xb1,
	0x32, 0x27, 0x3f, 0x31, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x15, 0xd2, 0xe2,
	0x12, 0x84, 0x32, 0xe3, 0x8b, 0x53, 0xf3, 0x4a, 0xe2, 0x4b, 0x32, 0x73, 0x53, 0x25, 0x98, 0x15,
	0x18, 0x35, 0x98, 0x83, 0xf8, 0xa1, 0x12, 0xc1, 0xa9, 0x79, 0x25, 0x21, 0x99, 0xb9, 0xa9, 0x49,
	0x6c, 0x60, 0xbb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x3d, 0x09, 0xa5, 0x86, 0x00,
	0x00, 0x00,
}
